### ISSUE TITLE
Trouble Instantiating 

### ISSUE THREAD

**Issue by matrix45** [PoeticMediaLab/Annotator-Categories#1]
Hello,

Awesome job on this plugin! I was wondering if you could give me an example of the options that need to be set to that I can add it to the plugins. Just having a little bit a trouble knowing how to pass that object when adding the plugin. Thanks so much for your help and for sharing the plugin.

**Comment by mwidner** [comment]
Thanks, and excellent point. It's simply a list of category names, so annotation.category = ['category1', 'category2']
Usually, categories look best if they're short names and no more than 4, but you can adjust the CSS to your tastes.
