### ISSUE TITLE
install instruction

### ISSUE THREAD

**Issue by cwlinghk** [PoeticMediaLab/Annotator-Categories#2]
May I know is there any instructions on how to install the category plug-in? Thank you very much.

**Comment by mwidner** [comment]
To use this plugin, you would enable it in Annotator.js just as any other plugins, which is documented here: http://docs.annotatorjs.org/en/v1.2.x/getting-started.html#adding-more-plugins
So, download this code, put it with the Annotator.js code, then enable it using the sample code in the docs.
